### ISSUE TITLE
Integrating Venmo Ios sdk

### ISSUE THREAD

**Issue by rajkumarunified** [venmo/venmo-ios-sdk#89] opened 2015-07-30 08:00 UTC
duplicate symbols for architecture i386.
duplicate symbol _VENErrorDomainHTTPResponse in:
    /Users/sachita/Library/Developer/Xcode/DerivedData/TutorApp-bpcgdwgtpngcjbeirvsjggoyudbn/Build/Intermediates/TutorApp.build/Debug-iphonesimulator/TutorApp.build/Objects-normal/i386/RegisterAsStudentViewController.o
    /Users/sachita/Library/Developer/Xcode/DerivedData/TutorApp-bpcgdwgtpngcjbeirvsjggoyudbn/Build/Products/Debug-iphonesimulator/libPods-TutorApp-VENCore.a(VENHTTPResponse.o)

I am using ASIHTTP request for our web services and facing architecture issue. 
![screen shot 2015-07-30 at 1 26 32 pm](https://cloud.githubusercontent.com/assets/8428386/8978366/2cfbfc12-36bf-11e5-91f5-3ee5b251e588.png)

**Comment by adomanico** [comment] 2015-11-03 16:56
Also seeing this issue (not using ASIHTTP though)

**Comment by eliperkins** [comment] 2015-11-11 20:10
Closing as a dupe of #78. Feel free to track there!

**Closed by eliperkins** 2015-11-11 20:10 UTC
